config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :transport_modes, only: [:index, :new, :create, :show, :edit, :update] do
    resources :weight_rates, only: [:index, :new, :create]
    resources :distance_rates, only: [:index, :new, :create]
    resources :delivery_deadlines, only: [:index, :new, :create]
  end

  resources :vehicles, only: [:index, :show, :new, :create, :edit, :update] do
    get 'search', on: :collection
  end

  resources :orders, only: [:index, :show, :new, :create, :edit, :update] do
    resources :order_freights, only: [:index, :new, :create] 
    post 'run', on: :member
    post 'close', on: :member
    get 'search', on: :collection
  end
 end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_freights
  has_many :transport_modes
  has_many :vehicles, through: :transport_modes

  enum status: [:pending, :running, :processing, :closed]
  enum delivery_final_status: [:on_time, :out_of_time]

  before_validation :generate_code, on: :create

  validates :pickup_address, :pickup_zipcode, :pickup_city, :pickup_state, :product_code, :product_dimension, :product_weight, :recipient_name, :recipient_phone, :deliver_address, :delivery_zipcode, :delivery_city, :delivery_state, :delivery_distance, presence: true

  def generate_code
    self.code = SecureRandom.alphanumeric(15).upcase
  end

  def run_freights_calculator
    @order = Order.find(id)
    @transport_modes = TransportMode.all
    order_id = @order.id
    weight = @order.product_weight
    distance = @order.delivery_distance
    final_price = 0
    final_deadline = 0
    @transport_modes.each do |tm|
      if tm.active?
        if weight > tm.min_weight && weight <= tm.max_weight
          if distance > tm.min_distance && distance <= tm.max_distance
            final_price = tm.price_calculator(tm,weight,distance)
            final_deadline = tm.calculate_final_deadline(tm,distance)
            transport_mode_id = tm.id
            OrderFreight.create!(order_id: @order.id, transport_mode_id: transport_mode_id, final_price:final_price, final_deadline: final_deadline, run_date: Date.today)
          end
        end
      end
    end
  end

 
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :unbook_vehicle, only: [:close]

  def new
    @order = Order.new
  end

  def create
    order_params = params.require(:order).permit(:pickup_address, :pickup_zipcode, :pickup_city, :pickup_state, :product_code, :product_dimension, :product_weight, :recipient_name, :recipient_phone, :deliver_address, :delivery_zipcode, :delivery_city, :delivery_state, :delivery_distance)
    @order = Order.new(order_params)
    @order.user = current_user
    @orders = Order.all
    if @order.save
      redirect_to @order, notice: 'Pedido registrado com sucesso'
    else
      flash.now[:alert] = 'Não foi possível registrar o pedido'
      render :new
    end
  end

  def index
    @orders = Order.all
    @pending_orders = Order.all.where(status: :pending)
    @running_orders = Order.all.where(status: :running)
    @processing_orders = Order.all.where(status: :processing)
    @closed_orders = Order.all.where(status: :closed)
  end

  def show
    @order = Order.find(params[:id])
  end

  def edit
    @order = Order.find(params[:id])
    @order_freights = OrderFreight.all
    @transport_modes = TransportMode.all
  end
  
  def run 
    @order = Order.find(params[:id])
    @order.running!
    @order.run_freights_calculator
    redirect_to edit_order_path
  end

  def update
    @order = Order.find(params[:id])
    if @order.running?
      order_freight_id = params["of_id"]
      @order_freight = OrderFreight.find(order_freight_id)
      set_and_update_variables()
      @order.processing!
      redirect_to @order, notice: 'Seleção realizada com sucesso'
      return
    end
    if @order.processing?
      order_params = params.require(:order).permit(:order_closing_date, :delivery_final_status, :justification)
      @order.closed!
      @order.update!(order_params)
      unbook_vehicle()
      redirect_to @order, notice: 'Encerramento concluído com sucesso'
      return
    end
  end

  def set_and_update_variables
    order_final_price = @order_freight.final_price
    order_final_deadline = @order_freight.final_deadline
    order_run_date = Date.today
    order_final_vehicle = set_vehicle()
    order_params = {order_final_price: order_final_price, order_final_deadline: order_final_deadline, order_run_date: order_run_date, order_final_vehicle: order_final_vehicle}
    @order.update!(order_params)
  end

  def set_vehicle
    tm_id = @order_freight.transport_mode_id
    @transport_mode = TransportMode.find(tm_id)
    @vehicle = Vehicle.find_by(transport_mode_id: tm_id, availability: 0)
    @vehicle.reserved!
    @vehicle.license
  end

  def close
    @order = Order.find(params[:id])
  end

  def unbook_vehicle
    @order = Order.find(params[:id])
    license = @order.order_final_vehicle
    @vehicle = Vehicle.find_by(license: license)
    @vehicle.available!
  end

  def search
    @code = params["query"]
    @order = Order.find_by("code LIKE ?", "%#{@code}%")
  end
end  

app/views/orders/close.html.erb
<h4><%= t '.title' %></h4>
<%= link_to (t '.back'), orders_path, :class => "btn btn-danger" %>

<%= form_with(model: @order) do |f| %>
  <h5><%= t '.subtitle' %> <%= @order.code%><br/>
  <br/>
  <div>
    <%= f.label :order_closing_date, :class => "form-label" %>
    <%= f.date_field :order_closing_date, :class => "form-control"%>
  </div>
  <br/>
  <div>
    <%= f.label :delivery_final_status, :class => "form-label" %>
    <%= f.select :delivery_final_status, options_for_select(Order.delivery_final_statuses.keys.map {|k| [I18n.t(k), k]}) %>
  </div>
  <br/>
  <p><%= t '.message'%></p>
  <br/>
  <div>
    <%= f.label :justification, :class => "form-label" %>
    <%= f.text_area :justification, :class => "form-control"%>
  </div>
  <% if @order.processing? %>
    <%= f.submit (t '.register'), :class => "btn btn-danger" %>
  <% end %>
<% end %>

app/views/orders/edit.html.erb
<%= link_to (t '.back'), orders_path, :class => "btn btn-danger" %>
<h4><%= t '.title' %></h4><br/>
<div>
  <h5><%= t '.subtitle' %>: <%= @order.code %></h5><br/>
  <div>
    <p class="text-danger"><%= t '.pickup_section' %></p>
    <p><%= t '.ps_address' %>: <%= @order.pickup_address %></p>
    <p><%= t '.ps_zipcode' %>: <%= @order.pickup_zipcode %></p>
    <p><%= t '.ps_city' %>: <%= @order.pickup_city %></p>
    <p><%= t '.ps_state' %>: <%= @order.pickup_state %></p><br/>
  </div>
  <div>
    <p class="text-danger"><%= t '.product_section' %></p>
    <p><%= t '.pr_code' %>: <%= @order.product_code %></p>
    <p><%= t '.pr_dimension' %>: <%= @order.product_dimension %> <%= t '.cubic_meters' %></p>
    <p><%= t '.pr_weight' %>: <%= @order.product_weight %> <%= t '.kg' %></p><br/>
  </div>
  <div>
    <p class="text-danger"><%= t '.destination_section' %>
    <p><%= t '.ds_recipient_name' %>: <%= @order.recipient_name %></p>
    <p><%= t '.ds_recipient_phone' %>: <%= @order.recipient_phone %></p>
    <p><%= t '.ds_address' %>: <%= @order.deliver_address %></p>
    <p><%= t '.ds_zipcode' %>: <%= @order.delivery_zipcode %></p>
    <p><%= t '.ds_city' %>: <%= @order.delivery_city %></p>
    <p><%= t '.ds_state' %>: <%= @order.delivery_state %></p>
    <p><%= t '.ds_distance' %>: <%= @order.delivery_distance %> <%= t '.km' %></p><br/>
  </div>
  <div>
    <p><%= t '.order_status' %>: <%= I18n.translate(@order.status) %></p>
    <p><%= t '.user_name' %>: <%= @order.user.name %></p><br/>
  </div>
</div>
<% if @order.running? %>
  <h4 class="text-danger"><%= t '.select_transport_option'%></h4><br/>
  <div>
    <%= form_tag url_for(action: 'update'), method: "patch" do %>
      <% @order.order_freights.each do |of| %>
        <div class="freights_options">
          <%= radio_button_tag 'of_id', of.id %>  <%= submit_tag "escolher" %><br/>
          <br/>
          <p><%= t '.tm_name' %>: <%= of.transport_mode.name %></p>
          <p><%= t '.final_price' %>: <%= t '.currency' %> <%= of.final_price %><%= t '.centimes' %></p>
          <p><%= t '.final_deadline' %>: <%= of.final_deadline %> <%= t '.day' %></p>
        </div>
      <% end %>
      <br/>
    <% end %>
  </div>
<% end %>

app/views/orders/index.html.erb
<h4><%= t '.title' %></h4><br/>
<div>
  <% if @orders.any? %>
    <div>
      <% @pending_orders.each do |order| %>
        <h5 class="text-danger"><%= t '.pending_orders' %></h5><br/>
        <h5><%= t '.subtitle' %>: <%= link_to(order.code, order_path(order.id)) %></h5>
        <div>
          <p><%= t '.ds_recipient_name' %>: <%= order.recipient_name %></p>
          <p><%= t '.ds_recipient_phone' %>: <%= order.recipient_phone %></p>
          <p><%= t '.pr_code' %>: <%= order.product_code %></p>
          <p><%= t '.order_status' %>: <%= I18n.translate(order.status) %></p>
          <p><%= t '.user_name' %>: <%= order.user.name %></p><br/>
        </div>
      <% end %>
    </div>
    <div>
      <% @running_orders.each do |order| %>
        <h5 class="text-danger"><%= t '.running_orders' %></h5><br/>
        <h5><%= t '.subtitle' %>: <%= link_to(order.code, order_path(order.id)) %></h5>
        <div>
          <p><%= t '.ds_recipient_name' %>: <%= order.recipient_name %></p>
          <p><%= t '.ds_recipient_phone' %>: <%= order.recipient_phone %></p>
          <p><%= t '.pr_code' %>: <%= order.product_code %></p>
          <p><%= t '.order_status' %>: <%= I18n.translate(order.status) %></p>
          <p><%= t '.user_name' %>: <%= order.user.name %></p><br/>
        </div>
      <% end %>
    </div>
    <div>
      <% @processing_orders.each do |order| %>
        <h5 class="text-danger"><%= t '.processing_orders' %></h5><br/>
        <h5><%= t '.subtitle' %>: <%= link_to(order.code, order_path(order.id)) %></h5>
        <div>
          <p><%= t '.ds_recipient_name' %>: <%= order.recipient_name %></p>
          <p><%= t '.ds_recipient_phone' %>: <%= order.recipient_phone %></p>
          <p><%= t '.pr_code' %>: <%= order.product_code %></p>
          <p><%= t '.order_status' %>: <%= I18n.translate(order.status) %></p>
          <p><%= t '.user_name' %>: <%= order.user.name %></p><br/>
        </div>
      <% end %>
    </div>
    <div>
      <% @closed_orders.each do |order| %>
        <h5 class="text-danger"><%= t '.closed_orders' %></h5><br/>
        <h5><%= t '.subtitle' %>: <%= link_to(order.code, order_path(order.id)) %></h5>
        <div>
          <p><%= t '.ds_recipient_name' %>: <%= order.recipient_name %></p>
          <p><%= t '.ds_recipient_phone' %>: <%= order.recipient_phone %></p>
          <p><%= t '.pr_code' %>: <%= order.product_code %></p>
          <p><%= t '.order_status' %>: <%= I18n.translate(order.status) %></p>
          <p><%= t '.user_name' %>: <%= order.user.name %></p><br/>
        </div>
      <% end %>
    </div>
  <% else %>
    <p><%= t '.message' %></p>
  <% end %>
</div>

app/views/orders/new.html.erb
<h4><%= t '.title' %></h4>
<%= link_to (t '.back'), root_path, :class => "btn btn-danger" %>

<%= form_with(model: @order) do |f| %>
  <div id="pickup">
    <div>
      <%= f.label :pickup_address, :class => "form-label" %>
      <%= f.text_field :pickup_address, :class => "form-control"%>
    </div>
    <div>
      <%= f.label :pickup_zipcode, :class => "form-label" %>
      <%= f.text_field :pickup_zipcode, :class => "form-control"%>
    </div>
    <div>
      <%= f.label :pickup_city, :class => "form-label" %>
      <%= f.text_field :pickup_city, :class => "form-control"%>
    </div>
    <div>
      <%= f.label :pickup_state, :class => "form-label" %>
      <%= f.text_field :pickup_state, :class => "form-control"%>
    </div>
  </div>
  <div id="product">
    <div>
      <%= f.label :product_code, :class => "form-label" %>
      <%= f.text_field :product_code, :class => "form-control"%>
    </div>
    <div>
      <%= f.label :product_dimension, :class => "form-label" %>
      <%= f.number_field :product_dimension, :class => "form-control"%>
    </div>
    <div>
      <%= f.label :product_weight, :class => "form-label" %>
      <%= f.number_field :product_weight, :class => "form-control"%>
    </div>
  </div>
  <div id="recipient">
    <div>
      <%= f.label :recipient_name, :class => "form-label" %>
      <%= f.text_field :recipient_name, :class => "form-control"%>
    </div>
    <div>
      <%= f.label :recipient_phone, :class => "form-label" %>
      <%= f.text_field :recipient_phone, :class => "form-control"%>
    </div>
    <div>
      <%= f.label :deliver_address, :class => "form-label" %>
      <%= f.text_field :deliver_address, :class => "form-control"%>
    </div>
    <div>
      <%= f.label :delivery_zipcode, :class => "form-label" %>
      <%= f.text_field :delivery_zipcode, :class => "form-control"%>
    </div>
    <div>
      <%= f.label :delivery_city, :class => "form-label" %>
      <%= f.text_field :delivery_city, :class => "form-control"%>
    </div>
    <div>
      <%= f.label :delivery_state, :class => "form-label" %>
      <%= f.text_field :delivery_state, :class => "form-control"%>
    </div>
    <div>
      <%= f.label :delivery_distance, :class => "form-label" %>
      <%= f.number_field :delivery_distance, :class => "form-control"%>
    </div>
  </div>
  <%= f.submit (t '.submit'), :class => "btn btn-danger" %>
<% end %>

app/views/orders/search.html.erb
<h4><%= t '.title' %></h4>
<section class="order_search">
  <div>
    <%= form_with(url: search_orders_path, method: :get) do |f| %>
      <%= f.label :query, (t '.order_search'), :class => "form-label" %>
      <%= f.text_field :query, :class => "form-control" %>
      <%= f.submit (t '.search'), :class => "btn btn-danger" %>
    <% end %>
  </div>
  <div>
    <% if @order.present? %>
      
      <h5><%= t '.subtitle' %>: <%= @order.code %></h5><br/>
      <p><%= t '.run_date' %>: <%= I18n.l @order.order_run_date %></p>
      <p><%= t '.final_deadline' %>: <%= @order.order_final_deadline %> <%= t '.day' %></p>
      <p><%= t '.estimated_delivery_date' %>: <%= I18n.l (@order.order_run_date + @order.order_final_deadline) %></p>
      <p><%= t '.reserved_vehicle' %>: <%= @order.order_final_vehicle %></p>
      <p><%= t '.order_status' %>: <%= I18n.translate(@order.status) %></p>
    <% else %>
      <%= t '.fail' %>
    <% end %>
  </div>
</section>

app/views/orders/show.html.erb
<%= link_to (t '.back'), orders_path, :class => "btn btn-danger" %>
<h4><%= t '.title' %></h4><br/>
<div>
  <h5><%= t '.subtitle' %>: <%= @order.code %></h5><br/>
  <br/>
  <div>
    <p><%= t '.order_status' %>: <%= I18n.translate(@order.status) %></p>
    <p><%= t '.user_name' %>: <%= @order.user.name %></p><br/>
  </div>
  <br/>
  <div>
    <p class="text-danger"><%= t '.pickup_section' %></p>
    <p><%= t '.ps_address' %>: <%= @order.pickup_address %></p>
    <p><%= t '.ps_zipcode' %>: <%= @order.pickup_zipcode %></p>
    <p><%= t '.ps_city' %>: <%= @order.pickup_city %></p>
    <p><%= t '.ps_state' %>: <%= @order.pickup_state %></p><br/>
  </div>
  <div>
    <p class="text-danger"><%= t '.product_section' %></p>
    <p><%= t '.pr_code' %>: <%= @order.product_code %></p>
    <p><%= t '.pr_dimension' %>: <%= @order.product_dimension %> <%= t '.cubic_meters' %></p>
    <p><%= t '.pr_weight' %>: <%= @order.product_weight %> <%= t '.kg' %></p><br/>
  </div>
  <div>
    <p class="text-danger"><%= t '.destination_section' %>
    <p><%= t '.ds_recipient_name' %>: <%= @order.recipient_name %></p>
    <p><%= t '.ds_recipient_phone' %>: <%= @order.recipient_phone %></p>
    <p><%= t '.ds_address' %>: <%= @order.deliver_address %></p>
    <p><%= t '.ds_zipcode' %>: <%= @order.delivery_zipcode %></p>
    <p><%= t '.ds_city' %>: <%= @order.delivery_city %></p>
    <p><%= t '.ds_state' %>: <%= @order.delivery_state %></p>
    <p><%= t '.ds_distance' %>: <%= @order.delivery_distance %> <%= t '.km' %></p><br/>
  </div>
</div>
<% if @order.pending? %>
  <%= button_to (t '.run_order'), run_order_path(@order.id), :class => "btn btn-danger" %>
<% end %>
<% if @order.running? %>
  <%= link_to 'Escolher Opção de Frete', edit_order_path(@order.id), :class => "btn btn-danger" %>
<% end %>

<% if @order.processing? || @order.closed? %>
  <div>
    <p class="text-danger"><%= t '.infos' %></p>
    <p><%= t '.run_date' %>: <%= I18n.l @order.order_run_date %></p>
    <p><%= t '.final_price' %>: <%= t '.currency' %> <%= @order.order_final_price %><%= t '.centimes' %></p>
    <p><%= t '.final_deadline' %>: <%= @order.order_final_deadline %> <%= t '.day' %></p>
    <br/>
  </div>
  <% if @order.processing? %>
    <%= button_to (t '.close_order'), close_order_path(@order.id), :class => "btn btn-danger" %>
  <% end %>
<% end %>

<% if @order.closed? %>
  <div>
    <p><%= t '.order_closing_date' %>: <%= I18n.l @order.order_closing_date %></p>
    <p><%= t '.delivery_final_status' %>: <%= I18n.translate(@order.delivery_final_status) %></p>
    <p><%= t '.justification' %>: <%= @order.justification %></p>
<% end %>
<br/>