config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :transport_modes, only: [:index, :new, :create, :show, :edit, :update] do
    resources :weight_rates, only: [:index, :new, :create]
    resources :distance_rates, only: [:index, :new, :create]
    resources :delivery_deadlines, only: [:index, :new, :create]
  end

  resources :vehicles, only: [:index, :show, :new, :create, :edit, :update] do
    get 'search', on: :collection
  end

  resources :orders, only: [:index, :show, :new, :create, :edit, :update] do
    resources :order_freights, only: [:index, :new, :create] 
    post 'run', on: :member
    post 'close', on: :member
    get 'search', on: :collection
  end
 end

app/models/transport_mode.rb
class TransportMode < ApplicationRecord
  has_many :vehicles
  has_many :weight_rates
  has_many :distance_rates
  has_many :delivery_deadlines
  has_many :order_freights

  validates :name, uniqueness: true

  validates :name, :min_distance, :max_distance, :min_weight, :max_weight, :fixed_rate, presence: true

  validates :min_distance, :max_distance, :max_weight, :fixed_rate, numericality: {greater_than: 0}

  enum status: {active: 0, inactive: 1}

 
  def price_calculator(tm, weight,distance)
    a = 0
    b = 0
    tm.weight_rates.each do |wr|
      if weight > wr.min_weight_range && weight <= wr.max_weight_range
        a = wr.price_kg * weight
      end
    end
    tm.distance_rates.each do |dr|
      if distance > dr.min_distance_rate && distance <= dr.max_distance_rate
        b = dr.price
      end
    end
    a + b + tm.fixed_rate
  end
  

  def calculate_final_deadline(tm, distance)
    d = 0
    tm.delivery_deadlines.each do |dd|
      if distance > dd.min_delivery_distance && distance <= dd.max_delivery_distance
        d = dd.deadline
      end
    end
    d
  end
end

app/controllers/transport_modes_controller.rb
class TransportModesController < ApplicationController
  before_action :authenticate_user!

  def index
    @transport_modes = TransportMode.all
  end
  
  def new
    @transport_mode = TransportMode.new
  end

  def create
    transport_mode_params = params.require(:transport_mode).permit(:name, :min_distance, :max_distance, :min_weight, :max_weight, :fixed_rate, :status)

    @transport_mode = TransportMode.new(transport_mode_params)
    
    if @transport_mode.save
      redirect_to @transport_mode, notice: t('.success')
    else
      flash.now[:alert] = t('.fail')
      render :new
    end
  end

  def show
    @transport_mode = TransportMode.find(params[:id])
  end

  def edit
    @transport_mode = TransportMode.find(params[:id])
  end

  def update
    @transport_mode = TransportMode.find(params[:id])
    transport_mode_params = params.require(:transport_mode).permit(:name, :min_distance, :max_distance, :min_weight, :max_weight, :fixed_rate, :status)
    @transport_mode.update(transport_mode_params)
    redirect_to @transport_mode, notice: t('.registered')
  end
end

app/views/transport_modes/_form.html.erb
<%= form_with(model: @transport_mode) do |f| %>
  <div>
    <%= f.label :name, :class => "form-label" %>
    <%= f.text_field :name, :class => "form-control"%>
  </div>
  <div>
    <%= f.label :min_distance, :class => "form-label" %>
    <%= f.number_field :min_distance, :class => "form-control" %>
  </div>
  <div>
    <%= f.label :max_distance, :class => "form-label" %>
    <%= f.number_field :max_distance, :class => "form-control" %>
  </div>
  <div>
    <%= f.label :min_weight, :class => "form-label" %>
    <%= f.number_field :min_weight, :class => "form-control" %>
  </div>
  <div>
    <%= f.label :max_weight, :class => "form-label" %>
    <%= f.number_field :max_weight, :class => "form-control" %>
  </div>
  <div>
    <%= f.label :fixed_rate, :class => "form-label" %>
    <%= f.number_field :fixed_rate, :class => "form-control" %>
  </div>
  <%= f.submit (t '.submit'), :class => "btn btn-danger" %>
<% end %>

app/views/transport_modes/edit.html.erb
<h4><%= t '.title' %></h4>
<%= link_to (t '.back'), transport_modes_path, :class => "btn btn-danger" %>

<%= render 'form' %>

app/views/transport_modes/index.html.erb
<h4><%= t '.title' %></h4><br/>
<div>
<% if @transport_modes.any? %>
    <% @transport_modes.each do |tm| %>
      <h5><%= t '.name' %>: <%= link_to(tm.name, transport_mode_path(tm.id)) %></h5>
      <p><%= t '.min_distance' %>: <%= tm.min_distance %> <%= t '.km' %> - <%= t '.max_distance' %>: <%= tm.max_distance %> <%= t '.km' %></p>
      <p><%= t '.min_weight' %>: <%= tm.min_weight %> <%= t '.kg' %> - <%= t '.max_weight' %>: <%= tm.max_weight %> <%= t '.kg' %></p>
      <p><%= t '.fixed_rate' %>: <%= t '.$' %> <%= tm.fixed_rate %><%= t '.centimes' %> - <%= t '.status' %>: <%= I18n.translate(tm.status) %></p><br/>
    <% end %>
<% else %>
  <p><%= t '.message' %></p>
<% end %>
</div>
<div>
  <% if current_user.admin? %>
    <%= link_to (t '.register'), new_transport_mode_path, :class => "btn btn-danger" %>
  <% end %>
</div>

app/views/transport_modes/new.html.erb
<h4><%= t '.title' %></h4>
<%= link_to (t '.back'), transport_modes_path, :class => "btn btn-danger" %>

<%= render 'form' %>

app/views/transport_modes/show.html.erb
<%= link_to (t '.back'), transport_modes_path, :class => "btn btn-danger" %>
<h2><%= t '.title' %>: <%= @transport_mode.name %></h2>

<dl>
  <dt><%= TransportMode.human_attribute_name(:name) %></dt>
  <dd><%= @transport_mode.name %></dd>
  <dt><%= TransportMode.human_attribute_name(:min_distance) %>: </dt>
  <dd><%= @transport_mode.min_distance %> <%= t '.km' %></dd>
  <dt><%= TransportMode.human_attribute_name(:max_distance) %>: </dt>
  <dd><%= @transport_mode.max_distance %> <%= t '.km' %></dd>
  <dt><%= TransportMode.human_attribute_name(:min_weight) %>: </dt>
  <dd><%= @transport_mode.min_weight %> <%= t '.kg' %></dd>
  <dt><%= TransportMode.human_attribute_name(:max_weight) %>: </dt>
  <dd><%= @transport_mode.max_weight %> <%= t '.kg' %></dd>
  <dt><%= TransportMode.human_attribute_name(:fixed_rate) %>: </dt>
  <dd><%= t '.$' %> <%= @transport_mode.fixed_rate %><%= t '.centimes' %></dd>
  <dt><%= TransportMode.human_attribute_name(:status) %>: </dt>
  <dd><%= I18n.translate(@transport_mode.status) %></dd>
</dl>

  <div>
    <%= link_to (t '.weight_rate_index'), transport_mode_weight_rates_path(transport_mode_id: @transport_mode.id), :class => "btn btn-danger" %>
    <%= link_to (t '.distance_rate_index'), transport_mode_distance_rates_path(transport_mode_id: @transport_mode.id), :class => "btn btn-danger" %>
    <%= link_to (t '.delivery_deadline_index'), transport_mode_delivery_deadlines_path(transport_mode_id: @transport_mode.id), :class => "btn btn-danger" %>
  </div>
<% if current_user.admin? %>
  <div>
    <%= link_to (t '.edit'), edit_transport_mode_path(@transport_mode.id), :class => "btn btn-danger" %>
  </div>
  <div>
    <%= link_to (t '.weight_rate_new'), new_transport_mode_weight_rate_path(transport_mode_id: @transport_mode.id), :class => "btn btn-danger" %>
    <%= link_to (t '.distance_rate_new'), new_transport_mode_distance_rate_path(transport_mode_id: @transport_mode.id), :class => "btn btn-danger" %>
    <%= link_to (t '.delivery_deadline_new'), new_transport_mode_delivery_deadline_path(transport_mode_id: @transport_mode.id), :class => "btn btn-danger" %>
  </div>
<% end %>


  