config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :transport_modes, only: [:index, :new, :create, :show, :edit, :update] do
    resources :weight_rates, only: [:index, :new, :create]
    resources :distance_rates, only: [:index, :new, :create]
    resources :delivery_deadlines, only: [:index, :new, :create]
  end

  resources :vehicles, only: [:index, :show, :new, :create, :edit, :update] do
    get 'search', on: :collection
  end

  resources :orders, only: [:index, :show, :new, :create, :edit, :update] do
    resources :order_freights, only: [:index, :new, :create] 
    post 'run', on: :member
    post 'close', on: :member
    get 'search', on: :collection
  end
 end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :transport_mode
 
  enum availability: {available: 0, reserved: 1, maintenance: 2}

  validates :license, :brand, :model, :year, :max_load, presence: true
  validates :max_load, numericality: {greater_than: 0}
  validates :year, length: {is:4}
  validates :license, length: {is:7}
  validates :license, uniqueness: true
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :authenticate_user!

  def index
    @vehicles = Vehicle.all
  end

  def show
    @vehicle = Vehicle.find(params[:id])
  end

  def new
    @vehicle = Vehicle.new
    @transport_modes = TransportMode.all
  end

  def create
    vehicle_params = params.require(:vehicle).permit(:license, :brand, :model, :year, :max_load, :availability, :transport_mode_id)
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.save
      redirect_to @vehicle, notice: t('.success')
    else
      flash.now[:alert] = t('.fail')
      render :new
    end
  end

  def edit
    @vehicle = Vehicle.find(params[:id])
    @transport_modes = TransportMode.all
  end

  def update
    @vehicle = Vehicle.find(params[:id])
    vehicle_params = params.require(:vehicle).permit(:license, :brand, :model, :year, :max_load, :availability, :transport_mode_id)
    @vehicle.update(vehicle_params)
    redirect_to @vehicle, notice: t('.registered')
  end

  def search
    @license = params["query"]
    @vehicles = Vehicle.where("license LIKE ?", "%#{@license}%")
  end
end

app/views/vehicles/_form.html.erb
<%= form_with(model: @vehicle) do |f| %>
  <div>
    <%= f.label :transport_mode_id, :class => "form-label" %>
    <%= f.collection_select :transport_mode_id, @transport_modes, :id, :name, :class => "form-control" %>
  </div>
  <div>
    <%= f.label :license, :class => "form-label" %>
    <%= f.text_field :license, :class => "form-control" %>
  </div>
  <div>
    <%= f.label :brand, :class => "form-label" %>
    <%= f.text_field :brand, :class => "form-control" %>
  </div>
  <div>
    <%= f.label :model, :class => "form-label" %>
    <%= f.text_field :model, :class => "form-control" %>
  </div>
  <div>
    <%= f.label :year, :class => "form-label" %>
    <%= f.number_field :year, :class => "form-control" %>
  </div>
  <div>
    <%= f.label :max_load, :class => "form-label" %>
    <%= f.number_field :max_load, :class => "form-control" %>
  </div>
  <div>
    <%= f.label :availability, :class => "form-label" %>
    <%= f.select :availability, options_for_select(Vehicle.availabilities.keys.map {|k| [I18n.t(k), k]}) %>
  </div>
  <%= f.submit (t '.register'), :class => "btn btn-danger" %>
<% end %>

app/views/vehicles/edit.html.erb
<%= link_to (t '.back'), vehicles_path, :class => "btn btn-danger" %>
<h4><%= t '.title' %></h4>

<%= render 'form' %>

app/views/vehicles/index.html.erb
<h4><%= t '.title' %></h4>
<br/>
<div>
  <% if @vehicles.any? %>
    <% @vehicles.each do |v| %>
      <p><%= t '.transport_mode' %>: <%= v.transport_mode.name %>
      <p><%= t '.license' %>: <%= link_to(v.license, vehicle_path(v.id)) %></p>
      <p><%= t '.brand' %>: <%= v.brand %> - <%= t '.model' %>: <%= v.model %></p><br/>
    <% end %>
  <% else %>
    <p><%= t '.message' %></p>
  <% end %>
</div>
<div>
  <% if current_user.admin? %>
    <%= link_to (t '.register_new'), new_vehicle_path, :class => "btn btn-danger" %>
  <% end %>
</div>

app/views/vehicles/new.html.erb
<%= link_to (t '.back'), vehicles_path, :class => "btn btn-danger" %>
<h4><%= t '.title' %></h4>

<%= render 'form' %>

app/views/vehicles/search.html.erb
<section class="vehicle_search">
  <div>
    <% if user_signed_in? %>
      <%= form_with(url: search_vehicles_path, method: :get) do |f| %>
        <%= f.label :query, (t '.vehicle_search'), :class => "form-label" %>
        <%= f.text_field :query, :class => "form-control" %>
        <%= f.submit (t '.search'), :class => "btn btn-danger" %>
      <% end %>
    <% end %>
  </div>
  <div>
    <p><%= t '.search_result' %>:
    <% if @vehicles.present? %>
      <% @vehicles.each do |vehicle| %>
          <dl>
            <dt><%= Vehicle.human_attribute_name(:transport_mode) %>: </dt>
            <dd><%= vehicle.transport_mode.name %></dd>
            <dt><%= Vehicle.human_attribute_name(:license) %>: </dt>
            <dd><%= vehicle.license %></dd>
            <dt><%= Vehicle.human_attribute_name(:brand) %>: </dt>
            <dd><%= vehicle.brand %></dd>
            <dt><%= Vehicle.human_attribute_name(:model) %>: </dt>
            <dd><%= vehicle.model %></dd>
            <dt><%= Vehicle.human_attribute_name(:year) %>: </dt>
            <dd><%= vehicle.year %></dd>
            <dt><%= Vehicle.human_attribute_name(:max_load) %>: </dt>
            <dd><%= vehicle.max_load %> kg</dd>
            <dt><%= Vehicle.human_attribute_name(:availability) %>: </dt>
            <dd><%= I18n.translate(vehicle.availability) %></dd>
          </dl>
      <% end %>
    <% else %>
      <%= t '.fail' %>
    <% end %>
  </div>
</section>

app/views/vehicles/show.html.erb
<%= link_to (t '.back'), vehicles_path, :class => "btn btn-danger" %>
<h4><%= t '.title' %></h4>

<dl>
  <dt><%= Vehicle.human_attribute_name(:transport_mode) %>: </dt>
  <dd><%= @vehicle.transport_mode.name %></dd>
  <dt><%= Vehicle.human_attribute_name(:license) %>: </dt>
  <dd><%= @vehicle.license %></dd>
  <dt><%= Vehicle.human_attribute_name(:brand) %>: </dt>
  <dd><%= @vehicle.brand %></dd>
  <dt><%= Vehicle.human_attribute_name(:model) %>: </dt>
  <dd><%= @vehicle.model %></dd>
  <dt><%= Vehicle.human_attribute_name(:year) %>: </dt>
  <dd><%= @vehicle.year %></dd>
  <dt><%= Vehicle.human_attribute_name(:max_load) %>: </dt>
  <dd><%= @vehicle.max_load %> kg</dd>
  <dt><%= Vehicle.human_attribute_name(:availability) %>: </dt>
  <dd><%= I18n.translate(@vehicle.availability) %></dd>
</dl>

<% if current_user.admin? %>
  <%= link_to (t '.edit'), edit_vehicle_path(@vehicle.id), :class => "btn btn-danger" %>
<% end %>